fix: removed extra echoes and some small tuning

diff --git a/taito b/taito
--- a/taito
+++ b/taito
@@ -120,8 +120,8 @@ if ! (
 
   command="${params[0]}"
 
-  export taito_run="@asd!fef@"
-  export taito_run_fg="@asd!fg!fef@"
+  export taito_run=".fj45jgnv."
+  export taito_run_fg=".fekfj56hk."
   log_file=$(mktemp /tmp/taito-cli.XXXXXX)
   echo "-" > "${log_file}"
   # Command will execute 'docker commit' -> Start a background process
@@ -129,8 +129,7 @@ if ! (
   # is still running
   (
     # Read commands from log file and execute them
-    # | tr -cdu '\11\12\15\40-\176'
-    tail -f "${log_file}" | while read -r line; do
+    tail -f "${log_file}" | tr -cdu '\11\12\15\40-\176' | while read -r line; do
       c=$(echo "${line}" | grep "${taito_run}" \
         | sed "s/^.*${taito_run}\(.*\)${taito_run}.*$/\1/")
       if [[ ${c} != "" ]]; then
@@ -147,7 +146,7 @@ if ! (
   # Link database container if env is local and the command uses database
   # TODO: this is a quick hack
   if ( [[ ${command} == ":local" ]] || [[ ${command} != *":"* ]] ) && \
-     ( [[ ${command} == db* ]] || [[ ${command} == init ]] ) && \
+     ( [[ ${command} == db* ]] || [[ ${command} == o-init ]] ) && \
      [[ ${command} != db-add ]]; then
     if [[ ${mode} != "local" ]]; then
       link_flags="--link ${taito_project}-database:${taito_project}-database"
@@ -195,7 +194,6 @@ if ! (
       docker pull "${taito_image_name}"
     fi
 
-    echo ${entrypoint}
     # Run on docker
     # shellcheck disable=SC2086
     eval "docker run -it \
@@ -218,18 +216,18 @@ if ! (
   fi
 
   # Execute host commands on foreground. Commands are read from log file.
-  # TODO this is duplicate code
-  cat "${log_file}" | tr -cd '\11\12\15\40-\176' | while read -r line; do
-    c=$(echo "${line}" | grep "${taito_run_fg}" \
-      | sed "s/^.*${taito_run_fg}\(.*\)${taito_run_fg}.*$/\1/")
-    if [[ ${c} != "" ]]; then
-      # TODO confirm execution?
-      if ! eval "${c}"; then
-        echo "ERROR!"
-        exit 1
-      fi
+  c=$(cat "${log_file}" | grep "${taito_run_fg}" | \
+    sed "s/^.*${taito_run_fg}\(.*\)${taito_run_fg}.*$/\1/")
+  if [[ ${c} != "" ]]; then
+    # TODO confirm execution?
+    echo
+    echo "------------------------------------------------------------------------------------------"
+    echo
+    if ! eval "${c}"; then
+      echo "ERROR!"
+      exit 1
     fi
-  done
+  fi
 
   # Kill background execution process
   pgrep -f "${log_file}" | xargs kill &> /dev/null
