feat: untested digitalocean support

diff --git a/plugins/do/hooks/pre-50 b/plugins/do/hooks/pre-50
--- a/plugins/do/hooks/pre-50
+++ b/plugins/do/hooks/pre-50
@@ -1,5 +1,24 @@
 #!/bin/bash -e
+# shellcheck source=../lib/all.bash
+. "${taito_plugin_path:?}/lib/all.bash"
 
-echo "TODO: implement. See AWS and GCP for an example"
+# Authentication for CI
+if [[ ${taito_mode:-} == "ci" ]]; then
+  # Ensure that AWS credentials exist
+  if [[ ! "${DO_API_KEY}" ]]; then
+    taito::print_plugin_title
+    echo
+    echo "ERROR: DO_API_KEY environment variable not set."
+    echo "Configure DO_API_KEY in your CI/CD settings."
+    exit 1
+  fi
+
+  # Kubernetes (EKS) authentication
+  if [[ ${taito_command_requires_kubernetes:?} == "true" ]]; then
+    taito::print_plugin_title
+    echo "Getting credentials for Kubernetes"
+    do::authenticate_on_kubernetes
+  fi
+fi
 
 taito::call_next "${@}"
