fix: clean up descriptions output

diff --git a/plugins/ansible-zone/zone-apply-20 b/plugins/ansible-zone/zone-apply-20
--- a/plugins/ansible-zone/zone-apply-20
+++ b/plugins/ansible-zone/zone-apply-20
@@ -1,84 +1,86 @@
 #!/bin/bash -e
 : "${taito_host_uname:?}"
 
-name=${1}
+taito::confirm "Apply changes by running ansible scripts" || \
+  taito::skip_to_next
 
-function cleanup {
-  rm -f ansible-playbooks/taito-ansible.cfg &> /dev/null
-}
+(
+  function cleanup {
+    rm -f ansible-playbooks/taito-ansible.cfg &> /dev/null
+  }
+  trap cleanup EXIT
 
-if taito::confirm_execution "ansible" "${name}" \
-  "Apply changes by running ansible scripts"
-then
-  (
-    trap cleanup EXIT
-    ansible_options="${ansible_options:-}"
+  ansible_options="${ansible_options:-}"
 
-    echo "Inventories:"
-    ls -p ansible-playbooks | grep -v / | grep -v "\."
+  echo "Inventories:"
+  ls -p ansible-playbooks | grep -v / | grep -v "\."
+  echo
+  echo "Select inventory:"
+  read -r inventory
+  if [[ ${inventory} ]]; then
+    ansible_options="${ansible_options} -i ${inventory}"
+  fi
+
+  echo
+  echo "Groups and hosts in ansible inventory:"
+  grep "^\\[" "ansible-playbooks/${inventory}" | \
+    sed "s/\\[//" | \
+    sed "s/\\]//" | \
+    tr '\n' ' ' || \
+    :
+  echo
+  grep "^[a-z]" "ansible-playbooks/${inventory}" | sort | uniq
+  echo
+  echo "Enter limit for ansible (e.g. group or hostname) or leave empty to run"
+  echo "all in inventory '${inventory}':"
+  read -r limit
+  if [[ ${limit} ]]; then
+    ansible_options="${ansible_options} --limit ${limit}"
+  fi
+
+  echo "Enter SSH username or leave empty to use the default"
+    "[${taito_host_username:?}]:"
+  read -r username
+  ansible_options="$ansible_options -u ${username:-$taito_host_username}"
+
+  if [[ $username == "root" ]]; then
+    if taito::confirm "Log in with password"; then
+      ansible_options="$ansible_options --ask-pass"
+    fi
+  fi
+
+  if [[ -f "${HOME}/.ssh/config.taito" ]]; then
+    taito::executing_start
+    printf "[ssh_connection]\nssh_args = -F${HOME}/.ssh/config.taito\n" \
+      > ansible-playbooks/taito-ansible.cfg
+    export ANSIBLE_CONFIG="${PWD}/ansible-playbooks/taito-ansible.cfg"
+    set +x
+  elif [[ "${taito_host_uname}" == "Darwin" ]]; then
     echo
-    echo "Select inventory:"
-    read -r inventory
-    if [[ $inventory ]]; then
-      ansible_options="$ansible_options -i $inventory"
-    fi
+    echo "WARNING! ~/.ssh/config.taito file does not exist! SSH execution will"
+    echo "fail if your ~/.ssh/config file contains any macOS specific properties"
+    echo "(e.g. UseKeyChain)."
+  fi
 
+  cd ansible-playbooks
+  if [[ $ansible_options != *"--ask-pass"* ]]; then
+    # running ssh-add before ansible-playbook is required because otherwise
+    # ansible parallel execution asks for keyphrase for multiple servers at
+    # once and only one of them succeeds
+    echo "Enter SSH key name or leave empty to use the default [id_rsa]:"
+    read -r keyname
+    keyname=${keyname:-id_rsa}
+  fi
+
+  taito::execute_with_ssh_agent "
+    taito::executing_start
+    if [[ \"${keyname}\" ]]; then
+      ssh-add "${HOME}/.ssh/${keyname:-id_rsa}";
+    fi
     echo
-    echo "Groups and hosts in ansible inventory:"
-    grep "^\\[" ansible-playbooks/$inventory | sed "s/\\[//" | sed "s/\\]//" | tr '\n' ' ' || :
-    echo
-    grep "^[a-z]" ansible-playbooks/$inventory | sort | uniq
-    echo
-    echo "Enter limit for ansible (e.g. group or hostname) or leave empty to run"
-    echo "all in inventory '$inventory':"
-    read -r limit
-    if [[ $limit ]]; then
-      ansible_options="$ansible_options --limit $limit"
-    fi
-
-    echo "Enter SSH username or leave empty to use the default [${taito_host_username}]:"
-    read -r username
-    ansible_options="$ansible_options -u ${username:-$taito_host_username}"
-
-    if [[ $username == "root" ]]; then
-      if taito::confirm "Log in with password"; then
-        ansible_options="$ansible_options --ask-pass"
-      fi
-    fi
-
-    if [[ -f "${HOME}/.ssh/config.taito" ]]; then
-      ${taito_setv:?}
-      printf "[ssh_connection]\nssh_args = -F${HOME}/.ssh/config.taito\n" \
-        > ansible-playbooks/taito-ansible.cfg
-      export ANSIBLE_CONFIG="${PWD}/ansible-playbooks/taito-ansible.cfg"
-      set +x
-    elif [[ "${taito_host_uname}" == "Darwin" ]]; then
-      echo
-      echo "WARNING! ~/.ssh/config.taito file does not exist! SSH execution will"
-      echo "fail if your ~/.ssh/config file contains any macOS specific properties"
-      echo "(e.g. UseKeyChain)."
-    fi
-
-    cd ansible-playbooks
-    if [[ $ansible_options != *"--ask-pass"* ]]; then
-      # running ssh-add before ansible-playbook is required because otherwise
-      # ansible parallel execution asks for keyphrase for multiple servers at
-      # once and only one of them succeeds
-      echo "Enter SSH key name or leave empty to use the default [id_rsa]:"
-      read -r keyname
-      keyname=${keyname:-id_rsa}
-    fi
-
-    taito::execute_with_ssh_agent "
-      ${taito_setv:?}
-      if [[ \"${keyname}\" ]]; then
-        ssh-add "${HOME}/.ssh/${keyname:-id_rsa}";
-      fi
-      echo
-      echo Executing ansible playbooks...
-      ansible-playbook ${ansible_options:-} site.yml
-    "
-  )
-fi
+    echo Executing ansible playbooks...
+    ansible-playbook ${ansible_options:-} site.yml
+  "
+)
 
 taito::call_next "${@}"
diff --git a/plugins/helm/env-destroy-20 b/plugins/helm/env-destroy-20
--- a/plugins/helm/env-destroy-20
+++ b/plugins/helm/env-destroy-20
@@ -4,16 +4,14 @@
 # shellcheck source=../kubectl/lib/context.bash
 . "${taito_plugin_path:?}/../kubectl/lib/context.bash"
 
-name="${1}"
+taito::confirm \
+  "Delete and purge helm release ${taito_project}-${taito_target_env}" || \
+  taito::skip_to_next "${@}"
 
-if taito::confirm_execution "helm" "${name}" \
-  "Delete and purge helm release ${taito_project}-${taito_target_env}"
-then
-  kubectl::use-context
-  (
-    ${taito_setv:?}
-    helm::run delete --purge "${taito_project}-${taito_target_env}"
-  ) || echo "WARNING: Deleting helm release failed. Have you ever deployed?"
-fi
+kubectl::use_context
+(
+  taito::executing_start
+  helm::run delete --purge "${taito_project}-${taito_target_env}"
+) || echo "WARNING: Deleting helm release failed. Have you ever deployed?"
 
 taito::call_next "${@}"
