feat: do not silently skip missing taito_target on build/push

diff --git a/plugins/docker/artifact-release-50 b/plugins/docker/artifact-release-50
--- a/plugins/docker/artifact-release-50
+++ b/plugins/docker/artifact-release-50
@@ -26,7 +26,8 @@ echo "image: ${image}"
 if [[ -f ./taitoflag_images_exist ]]; then
   echo "Skipping artifact release. Image already exists in registry."
 elif [[ ${taito_targets:-} != *"${name}"* ]]; then
-  echo "Skipping artifact release. Artifact ${name} not included in taito_targets."
+  echo "ERROR: Artifact ${name} not included in taito_targets."
+  exit 1
 else
   if [[ -f "${name}.docker" ]]; then
     echo "Load ${name}.docker"
