wip: aws serverless

diff --git a/plugins/ssh/hooks/pre-50 b/plugins/ssh/hooks/pre-50
--- a/plugins/ssh/hooks/pre-50
+++ b/plugins/ssh/hooks/pre-50
@@ -15,11 +15,11 @@ for plugin_suffix in ${plugin_suffices[@]}; do
     forward_value=$(echo "$forward_value" | envsubst)
     (
       taito::executing_start
-      sh -c "ssh ${ssh_opts} -4 -f -o ExitOnForwardFailure=yes ${forward_value} sleep 60"
+      sh -c "ssh ${ssh_opts} -4 -f -o ExitOnForwardFailure=yes ${forward_value} sleep 2000"
     ) || (
-      echo "SSH connection failed with options ${ssh_opts} ${forward_value}."
-      exit 1
-    )
+      # TODO: Currently error is shown if proxy is already running
+      echo "WARN: SSH connection failed with options ${ssh_opts} ${forward_value}."
+    ) || :
     ssh_proxy_running="true"
   fi
 done
